In [2]:
import numpy as np

In [4]:
a=np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a.shape

(5, 2)

In [8]:
mean_a= np.mean(a,axis=0)
mean_a

array([2. , 8.4])

In [11]:
a_centered= a -mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [12]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [14]:
a_centered_sp / 4

2.0